// DO NOT EDIT THIS FILE!!! IT WILL BE AUTOMATICALLY GENERATED FROM src/i18n
/*global systemDictionary:true */
'use strict';

systemDictionary = {
  "settime": {
   "en": "Setting up the modem poll time..",
   "de": "Einstellen der Modem Umfrage Zeit.",
   "ru": "Установка времени опроса модема."
  },
  "Hilink adapter settings": {
   "de": "Beispiel",
   "ru": "Настройка драйвера Hilink"
  },
  "getip": {
   "en": "Setting ip address of the modem",
   "de": "Einstellung IP-Adresse des Modems",
   "ru": "Установка ip адрес модема"
  },
  "trafficInfo": {
   "en": "Traffic information",
   "de": "Verkehrsinformationen",
   "ru": "Информация о трафике"
  },
  "model": {
   "en": "Modem model",
   "de": "Modemmodell",
   "ru": "Модель модема"
  },
  "On save adapter restarts with new config immediately": {
   "de": "Beim Speichern von Einstellungen der Adapter wird sofort neu gestartet.",
   "ru": "Сразу после сохранения настроек драйвер перезапуститься с новыми значениями"
  }
};
